version: "3.8"

services:
  user-service:
    build:
      context: ./../user-service
      dockerfile: Dockerfile.userService
    restart: always
    ports:
      - "8020:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}?sslmode=disable"
      PORT: ${PORT}
      ENV: ${ENV}
    networks:
      - optimate_network

  optimizer-service:
    build:
      context: ./../optimizer-service
      dockerfile: Dockerfile.optimizerService
    restart: always
    ports:
      - "8021:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}?sslmode=disable"
      PORT: ${PORT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      DISK: ${DISK}
      ENV: ${ENV}
    networks:
      - optimate_network

  db:
    image: postgres:14
    container_name: optimate_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54331:5432"
    networks:
      - optimate_network

  minio:
    image: minio/minio
    container_name: optimate_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9700:9000"
      - "9007:9001"
    command: server /data --console-address ":9001" --address ":9000"
    volumes:
      - ./minio/data:/data
    networks:
      - optimate_network

networks:
  optimate_network:
    driver: bridge

volumes:
  db_data:
