version: "3.8"

services:
  user-service:
    build:
      context: ./../user-service
      dockerfile: Dockerfile.userService
    restart: always
    ports:
      - "8020:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}?sslmode=disable"

  db:
    image: postgres:14
    container_name: optimate_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54331:5432"
    networks:
      - optimate_network

networks:
  optimate_network:
    driver: bridge

volumes:
  db_data:
