definitions:
  handler.JSONResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: User service is running
      responses:
        "200":
          description: success
        "404":
          description: Not Found
      summary: User service is running
  /register:
    post:
      consumes:
      - application/json
      description: Register a new user
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "400":
          description: Failed to create user
          schema:
            $ref: '#/definitions/handler.JSONResponse'
        "409":
          description: Email already exists
          schema:
            $ref: '#/definitions/handler.JSONResponse'
      summary: Register a new user
swagger: "2.0"
