definitions:
  utils.JSONResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: Index Welcome
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      summary: Index Welcome
  /login:
    post:
      consumes:
      - application/json
      description: Login a user
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "401":
          description: Invalid password
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "500":
          description: Failed to create token
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      summary: Login a user
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload a file
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Successfully optimized the file
          schema:
            $ref: '#/definitions/utils.JSONResponse'
        "400":
          description: Error uploading file
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      summary: Upload a file
swagger: "2.0"
