name: Optimate CI

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Instal Go dependencies
      run: cd ./user-service && go mod tidy

    - name: Build
      run: go build -v ./user-service/cmd/api/main.go

    # - name: Test
    #   run: go test -v ./user-service/...
    #   env: