name: Optimate CI

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Install Go dependencies
      # run: cd ./user-service && go mod tidy && go mod download
      run: go mod tidy
      working-directory: user-service

    - name: Build
      run: go build -o user-service ./cmd/api/main.go
      working-directory: user-service

    # - name: Test
    #   run: go test -v ./user-service/...
    #   env: